### ISSUE TITLE
ES6 output

### ISSUE THREAD

**Issue by vphantom** [melange-re/melange#134] opened 2021-04-03 12:30 UTC
The question was raised in chat and probably deserves a more formal discussion.  The main points are:

* ES6 is widely supported in browsers (except tail call optimization), so gradually some features from it (like `let` and `=>`) could be added to the compiler.

* At that point, should we add a command line option to specify whether we want legacy ES5 or the new ES6 output, or should we deprecate ES5 output immediately? I never used `Babel` so I can't comment on its ES6-to-ES5 output vs Melange's current output, but since it exists I suppose jumping straight to ES6-only could be a solution. Then again if it's easy to keep ES5 output for a while with an optional command line option, it might be worthwhile.

I don't know the implications, so I'm just initiating the discussion here.

**Comment by anmonteiro** [comment] 2021-04-05 06:33
I'm not sure of all the implications of moving the output target to ES6.

I don't see many advantages of emitting ES6 right now. If someone is more knowledgeable, could you let me know, plase?

**Comment by EduardoRFS** [comment] 2021-04-05 08:51
@anmonteiro `let` and `arrow functions` are probably worth it, let will make some of our code less weird, like not having variables leaking the scope of a `for`, and arrow functions will probably decrease the bundlesize by a bit and the parsing size by another bit.

But both also matches the reason semantics almost 1 : 1. But we may want to use const instead of let for bindings.

```reason
let add = (a, b) => a + b;
````

Can literally be translated into 

```javascript
let add = (a, b) => a + b;
// or
const add = (a, b) => a + b;
```

**Comment by Kingdutch** [comment] 2021-04-05 17:48
Some other new things that can reduce the number of lines of code. I don't know whether they offer better performance but since they have a narrower intention the interpreter may be able to optimise better.

[Computed property names](https://caniuse.com/?search=computed%20property%20names)
```js
let x = 'some key';

// Old
var obj = { };
obj[x] = "My val";

// New in es6
const obj = { [x]: "My val" };
```
 
[Default parameters](https://caniuse.com/?search=default%20parameters)
```js
// Old
function (isHappy) {
  isHappy = typeof isHappy === "undefined" ? true : isHappy; // Can not use isHappy = isHappy || true
  if (isHappy) {
    clapHands();
  }
}

// New in es6
function (isHappy = true) {
  if (isHappy) {
    clapHands();
  }
}
```

**Comment by anmonteiro** [comment] 2021-04-05 18:06
I'm still not convinced by the arguments so far.

> and arrow functions will probably decrease the bundlesize by a bit 

GZIP takes care of that.

> Computed property names

Not clear what the benefit is here. Seems useful for dynamic things. We're not that.

> Default parameters

I'd be surprised if these didn't cause a perf hit.

**Comment by EduardoRFS** [comment] 2021-04-05 18:11
> GZIP takes care of that.

GZIP takes care only of bundle size, not the parsing size. But also changing to arrow functions remove nodes in the AST which is always nice.

> I'd be surprised if these didn't cause a perf hit.

I don't think they do, JS, especially because it's literally sugar to what we generate today already, even from an engine perspective. I would expect the performance to be identical on any recent engine, including JavaScript Core.

Also it can be easily transpiled if it matters for the user with babel.

[V8 post about faster calls](https://v8.dev/blog/adaptor-frame)

**Comment by Kingdutch** [comment] 2021-04-05 20:21
Although already a little older the following post talks about the efforts in early 2017 about bringing ES2015 features on par with ES5 speeds: https://v8.dev/blog/high-performance-es2015 Which is pretty much the discussion we’re having here :D

The article links to [Six Speed](https://github.com/kpdecker/six-speed) which tracks the performance of new JS features against their ES5 polyfill.

The [code is available on GitHub](https://github.com/kpdecker/six-speed) so it’s easy to check in the latest browsers and use to select which features would be an improvement.

**Comment by kanishka-work** [comment] 2021-05-23 17:18
I am still understanding the topic, so I may not have this right. Emitting es6 might help with using vite and native esm.

**Comment by thangngoc89** [comment] 2021-06-13 18:01
@Kingdutch that is a different story. ES Modules import/export are supported. The rest are still ES5

**Comment by bbenne10** [comment] 2023-11-14 14:59
Necrobumping! (but the issue is still open, so I think it's fine - I think we ought to close the issue if we're not soliciting more thoughts here)

 There's also the question of ES6-only APIs. In particular, I am thinking about web components. They rely on the ES6 class system and I don't think we presently have a way to wrap that up in a sufficiently backwards compatible manner in Melange. ReasonReact is nice, but there are definitely ways in which React has "leaked" in the past ~8 years or so and has influenced the standards process and it would be nice to be able to bind over those, wouldn't it?

**Comment by anmonteiro** [comment] 2024-04-05 00:01
in #1019, #1020 and #1059 we've started to emit `let` and `const` in the generated JS. The next Melange version emits ES6; there are technically no blockers for template string literal support.

**Closed by anmonteiro** 2024-04-05 00:01 UTC
Labels: question
